spring:
  application:
    name: spring-webflux
  webflux:
    base-path: /api
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/test
      database: test

server:
  port: 9000
  http2:
    enabled: true

logging:
  level:
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
